---
title: 'Project Title'
author: " (You are expected to give a descriptive title)"
date: " "
output:
  pdf_document: 
    toc: yes
    toc_depth: 4
    fig_caption: yes
    number_sections: yes
    fig_width: 3
    fig_height: 3
  word_document: 
    toc: yes
    toc_depth: 4
    fig_caption: yes
    keep_md: yes
  html_document: 
    toc: yes
    toc_depth: 4
    toc_float: yes
    number_sections: yes
    toc_collapsed: yes
    code_folding: hide
    code_download: yes
    smooth_scroll: yes
    theme: lumen
editor_options: 
  chunk_output_type: inline
---

```{=html}

<style type="text/css">

/* Cascading Style Sheets (CSS) is a stylesheet language used to describe the presentation of a document written in HTML or XML. it is a simple mechanism for adding style (e.g., fonts, colors, spacing) to Web documents. */

h1.title {  /* Title - font specifications of the report title */
  font-size: 24px;
  font-weight: bold;
  color: DarkRed;
  text-align: center;
  font-family: "Gill Sans", sans-serif;
}
h4.author { /* Header 4 - font specifications for authors  */
  font-size: 18px;
  font-family: system-ui;
  color: red;
  text-align: center;
}
h4.date { /* Header 4 - font specifications for the date  */
  font-size: 18px;
  font-family: system-ui;
  color: DarkBlue;
  text-align: center;
  font-weight: bold;
}
h1 { /* Header 1 - font specifications for level 1 section title  */
    font-size: 22px;
    font-family: "Times New Roman", Times, serif;
    color: navy;
    text-align: center;
    font-weight: bold;
}
h2 { /* Header 2 - font specifications for level 2 section title */
    font-size: 20px;
    font-family: "Times New Roman", Times, serif;
    color: navy;
    text-align: left;
    font-weight: bold;
}

h3 { /* Header 3 - font specifications of level 3 section title  */
    font-size: 18px;
    font-family: "Times New Roman", Times, serif;
    color: navy;
    text-align: left;
}

h4 { /* Header 4 - font specifications of level 4 section title  */
    font-size: 18px;
    font-family: "Times New Roman", Times, serif;
    color: darkred;
    text-align: left;
}

body { background-color:white; }

.highlightme { background-color:yellow; }

p { background-color:white; }

</style>
```

```{r setup, include=FALSE}
# code chunk specifies whether the R code, warnings, and output 
# will be included in the output files.
if (!require("knitr")) {
   install.packages("knitr")
   library(knitr)
}
if (!require("tidyverse")) {
   install.packages("tidyverse")
library(tidyverse)
}
if (!require("GGally")) {
   install.packages("GGally")
library(GGally)
}
knitr::opts_chunk$set(echo = TRUE,       # include code chunk in the output file
                      warning = FALSE,   # sometimes, you code may produce warning messages,
                                         # you can choose to include the warning messages in
                                         # the output file. 
                      results = TRUE,    # you can also decide whether to include the output
                                         # in the output file.
                      message = FALSE,
                      comment = NA
                      )  
```


\

# Introduction


This section is expected to address the following information:

* Some background information about the project: objective and motivation.

* Introduction to the working data set: sample size information about data collection, variables description (names, description/definition/type), etc.

* Clear statements of questions to be addressed (make sure both linear and logistic regression modeling will be used to address the questions).

# Methodology

Since this is a comprehensive analysis report, you are expected to use a standalone section to outline the methods and models that will be used to address the questions. Note that you are expected to write several narrative paragraphs to describe each of the potential models and their assumptions.

You can create subsections to describe individual models/algorithms.

# EDA and Feature Engineering

Feature engineering based on EDA. Other algorithm-based engineering methods are optional. If you have prior experience with any model-based algorithms, please feel free to use them to make powerful variables. Since this is a project focusing on statistical analysis, you need to consider the interpretation of regression models (i.e., coefficients). When using transformations, you need to think about the interpretation of the model.

## Handling Missing Value 

If your data set has missing values, you need to use appropriate imputation methods to handle missing values.

## Single Variable Distribution

Based on observed patterns from the visualizations, you may take appropriate actions such as regrouping, binning, discretization, etc. to make more powerful variables for subsequent models and algorithms.  

## Assessing Pairwised Relationship

Through observing the potential correlations decide whether to drop highly correlated variable(s). 


# Linear Regression Modeling

You are expected to follow the general model-building process to search for the final model to address related questions. Please include any visual representations whenever possible (see how visualizations were included in lecture notes).

## Create Candidate Models

See the section of the project guidelines.

## Use Cross-validation for Model Selection

Use cross-validation and MSE as a predictive performance measure to select the best model.

## Results and Conclusions

Report results based on the final model and conclude the statement of questions.


# Logistic Regression

Use the same model-building process as you did in the linear regression model to search for the best logistic regression model for prediction.

## Create Candidate Models

See the section in the project guidelines.

## Model Selection

Using ROC curve and AUC to compare candidate models. Both ROC curves and AUC need to be included in the report

## Cut-off Probability Search

Identify the optimal cut-off probability that yields the best prediction accuracy,

## Results and Conclusion

Report the results and conclusion of the logistic regression.

# Summary and Discussion

Summary of the project and discuss the strengths and weakness of the methods and potential improvements.

# Reference and Appendix

List all references cited in the project. Add any appendices you may have to support any arguments in the report.



